-- MySQL Script generated by MySQL Workbench
-- 08/21/19 19:47:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hachi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hachi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hachi` DEFAULT CHARACTER SET utf8 ;
USE `hachi` ;

-- -----------------------------------------------------
-- Table `hachi`.`state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hachi`.`state` (
  `id_state` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_state`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hachi`.`township`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hachi`.`township` (
  `id_township` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NOT NULL,
  `id_state` INT NOT NULL,
  PRIMARY KEY (`id_township`),
  INDEX `fk_municipio_estado_idx` (`id_state` ASC),
  CONSTRAINT `fk_township_state`
    FOREIGN KEY (`id_state`)
    REFERENCES `hachi`.`state` (`id_state`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hachi`.`town`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hachi`.`town` (
  `id_town` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NOT NULL,
  `id_township` INT NOT NULL,
  PRIMARY KEY (`id_town`),
  INDEX `fk_poblacion_municipio1_idx` (`id_township` ASC),
  CONSTRAINT `fk_town_township1`
    FOREIGN KEY (`id_township`)
    REFERENCES `hachi`.`township` (`id_township`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hachi`.`provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hachi`.`provider` (
  `id_provider` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_provider`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hachi`.`number_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hachi`.`number_type` (
  `id_number_type` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_number_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hachi`.`number`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hachi`.`number` (
  `id_number` INT NOT NULL AUTO_INCREMENT,
  `prefix` INT NOT NULL,
  `series` INT NOT NULL,
  `initial_numeration` INT NOT NULL,
  `final_numeration` INT NOT NULL,
  `id_provider` INT NOT NULL,
  `id_number_type` INT NOT NULL,
  `id_town` INT NOT NULL,
  INDEX `fk_numero_proveedor1_idx` (`id_provider` ASC),
  INDEX `fk_numero_tipo_numero1_idx` (`id_number_type` ASC),
  INDEX `fk_numero_poblacion1_idx` (`id_town` ASC),
  PRIMARY KEY (`id_number`),
  CONSTRAINT `fk_number_provider1`
    FOREIGN KEY (`id_provider`)
    REFERENCES `hachi`.`provider` (`id_provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_number_number_type1`
    FOREIGN KEY (`id_number_type`)
    REFERENCES `hachi`.`number_type` (`id_number_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_number_town1`
    FOREIGN KEY (`id_town`)
    REFERENCES `hachi`.`town` (`id_town`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hachi`.`user_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hachi`.`user_type` (
  `id_user_type` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_user_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hachi`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hachi`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(100) NOT NULL,
  `id_user_type` INT NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_user_user_type1_idx` (`id_user_type` ASC),
  CONSTRAINT `fk_user_user_type1`
    FOREIGN KEY (`id_user_type`)
    REFERENCES `hachi`.`user_type` (`id_user_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hachi`.`api_key`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hachi`.`api_key` (
  `id_api_key` INT NOT NULL AUTO_INCREMENT,
  `access_key` VARCHAR(150) NOT NULL,
  `access_secret` VARCHAR(150) NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_api_key`),
  INDEX `fk_api_key_user1_idx` (`id_user` ASC),
  CONSTRAINT `fk_api_key_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `hachi`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
